config/routes.rb
Rails.application.routes.draw do
  get  '/sign_in',  to: 'sessions#new',     as: :sign_in
  post '/sign_in',  to: 'sessions#create'

  get  '/sign_up',  to: 'users#new',        as: :sign_up
  post '/sign_up',  to: 'users#create'

  get  '/logout',   to: 'sessions#destroy', as: :logout

  namespace :manage do
    get '/', to: 'urls#index'
  end

  get '/:key', to: 'urls#original'
  post '/',    to: 'urls#create'


  root to: 'home#index'
end

app/models/url.rb
class Url < ActiveRecord::Base

  belongs_to :user

  validates :url, presence: true, format: { with: URI.regexp }

  def increment_number_of_visits!
    update_attribute(:number_of_visits, self.number_of_visits + 1)
  end

  def key
    Shortener.encode62(id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password, :password_confirmation

  has_many :urls

  validates :email,                 presence: true
  validates :password,              confirmation: true
  validates :password_confirmation, presence: true

  before_save do
    if password.present? && password_confirmation.present?
      self.encrypted_password, self.salt = Encryptor.sha1_and_salt(password)
    end
  end

  after_save do
    self.password = nil
  end

  def admin?
    role == 'admin'
  end

  def self.authenticate!(email, password)
    user = User.where(email: email).first
    return unless user

    encrypted = Encryptor.sha1(password, user.salt)
    User.where(encrypted_password: encrypted).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :build_current_user

  def domain_url
    "#{Settings.app_host}"
  end

  private

  def build_current_user
    return build_unauthenticated_current_user unless session[:user_id]

    user = User.find_by_id(session[:user_id])
    return build_unauthenticated_current_user unless user

    build_authenticated_current_user(user)
  end

  def build_authenticated_current_user(user)
    @current_user = OpenStruct.new({
      id: user.id,
      admin?: user.admin?,
      name: user.name,
      authenticated?: true
    })
  end

  def build_unauthenticated_current_user
    @current_user = OpenStruct.new({
      id: nil,
      admin?: false,
      name: nil,
      authenticated?: false
    })
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController

  before_action :check_authorization

  def check_authorization
    unless @current_user.authenticated?
      redirect_to sign_in_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.authenticate!(*user_params.values_at(:email, :password))
    if user
      session[:user_id] = user.id
      flash[:success] = 'Sign in successfully!'
      redirect_to manage_path
    else
      flash.now[:error] = 'Email/Password invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password).to_h
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def create
    model = Url.where(url: params[:url]).first

    if model.blank?
      model = Url.create(url: params[:url], user_id: @current_user.id)
    end

    if model.errors.present? && model.errors.messages[:url].present?
      return head :bad_request
    end

    encoded = Shortener.encode62(model.id)

    head :created, location: "#{domain_url}/#{encoded}"
  end

  def original
    id = Shortener.decode62(params[:key])

    if model = Url.find_by_id(id)
      model.increment_number_of_visits!
      redirect_to model.url
    else
      head :not_found
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from ActiveRecord::RecordNotUnique do
    flash.now[:error] = 'Account is taken'
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'User registered with success!'
      redirect_to manage_path
    else
      flash.now[:error] = user.errors.full_messages.join(',')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation).to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class='center'>
  <h1>URL Shortener</h1>

  <form id='shortenForm'>
    <input type='text' name='url' placeholder='Paste a link to shorten it' id='url'>
    <input type='submit' class='button' value=<%= t('buttons.shorten') %>>
    <p class='message'></p>
  </form>

</div>

<script type='text/javascript'>
  $(document).ready(function() {
    $('#shortenForm').submit(function(event) {
      $.ajax({
          type: 'POST',
          url: '/',
          data: { url: $('#url').val() },
          success: function(data, status, xhr) {
            $('#url').removeClass('inputError');
            $('#url').val(xhr.getResponseHeader('Location'))
            $('#url').select();
            $('p.message').text('Such a shortened url! Feel free to copy it!')
            $('p.message').show();
          },
          error: function(xhr) {
            console.log(xhr.status)
            if (xhr.status == 400)  {
              $('p.message').text('Invalid url');
              $('p.message').show();
              $('#url').addClass('inputError');
              $('#url').select();
            }
          }
      })

      event.preventDefault();
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YetAnotherUrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='menu'>
  <%= link_to t('shorten_it'), root_path %>

  <% if @current_user.authenticated? %>
    <%= link_to t('dashboard'), manage_path %>
    <%= link_to t('logout'), logout_path %>
    <p>Hello, <%= @current_user.name %></p>
  <% else %>
    <%= link_to t('sign_in'), sign_in_path %>
    <%= link_to t('sign_up'), sign_up_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <p class=<%= name %>><%= msg %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class='center'>
  <h1>Registration</h1>

  <form action='/sign_up' method='POST'>
    <input name="authenticity_token" type="hidden" value=<%= form_authenticity_token %> />
    <input type='text' name='user[name]'  placeholder='Name'>
    <input type='text' name='user[email]' placeholder='Email'>
    <input type='password' name='user[password]' placeholder='Type a password'>
    <input type='password' name='user[password_confirmation]' placeholder='Confirm the password'>
    <input type='submit' class='button' value=<%= t('buttons.register') %>>
    <p class='error hidden'></p>
  </form>

</div>